version: '3.8' # 表示该 Docker-Compose 文件使用的是 Version 3.8 file
services:
  php-fpm:
    build: ./app
    ports:
      - "9000:9000"
    links:
      - maria-db:maria-db
      - redis-db:redis-db
      - beanstalkd:beanstalkd
    volumes:
      - app-data:/var/www:rw
      - ./env/config/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ./env/logs/php-fpm:/var/log/php-fpm:rw
    restart: always
  nginx:
    image: nginx:latest
    depends_on:
        - php-fpm
    links:
      - php-fpm:php-fpm
    volumes:
      - app-data:/var/www:rw
      - ./env/config/nginx/conf.d:/etc/nginx/conf.d:ro
#      - ./env/config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./env/logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    restart: always
    command: nginx -g 'daemon off;'
  maria-db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql:rw
      - log-data:/var/lib/mysql-logs:rw
    environment:
      MYSQL_ROOT_PASSWORD: default
      MYSQL_DATABASE: default
      MYSQL_USER: default
      MYSQL_PASSWORD: default
    restart: always
  redis-db:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
  beanstalkd:
    build: ./env/beanstalkd
    ports:
      - "11300:11300"
    volumes:
      - beanstalkd-data:/data
    expose:
      - "9100"
volumes:
  redis-data: {}
  mysql-data: {}
  app-data: {}
  beanstalkd-data: {}
  log-data: {}
networks:
  back-end:
    external: true